### ISSUE TITLE
Keyboard not working on Android, but on the PC

### ISSUE THREAD

**Issue by aligator** [Dakkaron/Fairberry#14]
Hi, thanks for the great project!

I think I soldered everything correctly as it works flawlessly when connected to the PC. So the tiny connector should be ok.
But on the phone it just doesn't get recognized by android. The android settings say that no external keyboard is connected.

Do you have any idea how I could troubleshoot this problem?
I use Android 13 on a Fairphone 4 and also tried a Shift phone with Android 13... On both it doesn't work.

**Comment by aligator** [comment]
I think my USBC breakout board is somehow bad. It doesn't deliver 5V. Maybe it doesn't implement the USB standard correctly....
If I use an usb hub between the phone and the keyboard it works.

**Comment by Dakkaron** [comment]
That could very well be true. Did you check that your USB C breakout boards are USB OTG?

Since it's bidirectional, by default USBC doesn't output power. It needs to be configured so that the phone knows that it needs to power the USB connector.

**Comment by aligator** [comment]
If anyone else has this problem:

I just soldered a resistor ~5,1k between the CC pin and Ground and now it works.
Not easy though with these little pins. 
Basically i just added Flux and no new solder to it.

Make sure it does not touch the pins beside the CC pin.

![IMG_20240130_231344_1](https://github.com/Dakkaron/Fairberry/assets/663900/91582a13-0631-4c93-9117-3af15c52109c)

After that plug it in and check if it gives you now 5V.

Note that if it is done on one side only , the connector works only in one direction.
However that is ok here because i won't rotate the keyboard.

@Dakkaron maybe you add a note about this to the instructions?

**Comment by Dakkaron** [comment]
Congrats to your working keyboard!

Adding it to the documentation (maybe in a troubleshooting section) makes a lot of sense.
